# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'p4_ffa' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for p4_ffa
  pod 'Alamofire', '~> 4.7'
  pod 'SwiftyJSON', '~> 4.0'
  pod 'NVActivityIndicatorView'

end
